## YAML Template.
---
spring: 
    application:
        name: QRWedding
        
    datasource:
            driverClassName: org.postgresql.Driver
            url: jdbc:postgresql://83.212.105.54:5432/weddingqr
            username: admin
            password: Tech2015

            initialize: false
# Embedded Server Configuration (ServerProperties)
server:
    port: 8080